### ISSUE TITLE
Jco transpile: implementation of wasi-sockets for Node.js

### ISSUE THREAD

**Issue by pchickey** [bytecodealliance/jco#154]
## Tasks

- [x] `instance-network.instance-network`
- [x] `ip-name-lookup.resolve-addresses`
- [x] `ip-name-lookup.resolve-next-address`
- [x] `ip-name-lookup.drop-resolve-address-stream`
- [x] `ip-name-lookup.subscribe`
- [x] `tcp-create-socket.create-tcp-socket`
- [x] `tcp.start-bind`
- [x] `tcp.finish-bind`
- [x] `tcp.start-connect`
- [x] `tcp.finish-connect`
- [x] `tcp.start-listen`
- [x] `tcp.finish-listen`
- [x] `tcp.accept`
- [x] `tcp.local-address`
- [x] `tcp.remote-address`
- [x] `tcp.is-listening`
- [x] `tcp.address-family`
- [x] `tcp.ipv6-only`
- [x] `tcp.set-ipv6-only`
- [x] `tcp.set-listen-backlog-size`
- [x] `tcp.keep-alive-enabled`
- [x] `tcp.set-keep-alive-enabled`
- [x] `tcp.keep-alive-idle-time`
- [x] `tcp.set-keep-alive-idle-time`
- [x] `tcp.keep-alive-interval`
- [x] `tcp.set-keep-alive-interval`
- [x] `tcp.keep-alive-count`
- [x] `tcp.set-keep-alive-count`
- [x] `tcp.receive-buffer-size`
- [x] `tcp.set-receive-buffer-size`
- [x] `tcp.send-buffer-size`
- [x] `tcp.set-send-buffer-size`
- [x] `tcp.subscribe`
- [x] `tcp.shutdown`
- [x] `tcp[Symbol.dispose]()`
- [x] `udp-create-socket.create-udp-socket`
- [x] `udp.start-bind`
- [x] `udp.finish-bind`
- [x] `udp.start-connect`
- [x] `udp.finish-connect`
- [x] `udp.stream`
- [x] `udp.local-address`
- [x] `udp.remote-address`
- [x] `udp.address-family`
- [x] `udp.ipv6-only`
- [x] `udp.set-ipv6-only`
- [x] `udp.unicast-hop-limit`
- [x] `udp.set-unicast-hop-limit`
- [x] `udp.receive-buffer-size`
- [x] `udp.set-receive-buffer-size`
- [x] `udp.send-buffer-size`
- [x] `udp.set-send-buffer-size`
- [x] `udp.subscribe`
- [x] `udp[Symbol.dispose]()`
- [x] `incoming-datagram-stream.receive`
- [x] `incoming-datagram-stream.subscribe`
- [x] `outgoing-datagram-stream.send`
- [x] `outgoing-datagram-stream.subscribe`

### IP Lookup (1/1 test)
- [x] ℹ️ `preview2_ip_name_lookup` (may fail if `nameserver` is not set correctly - see `/etc/resolv.conf`)

### TCP (??/46 tests)
- [x] ✅`preview2_tcp_bind`
    - [x] ✅ test_tcp_bind_ephemeral_port(&net, IpAddress::IPV4_LOOPBACK);
    - [x] ✅ test_tcp_bind_ephemeral_port(&net, IpAddress::IPV6_LOOPBACK);
    - [x] ✅ test_tcp_bind_ephemeral_port(&net, IpAddress::IPV4_UNSPECIFIED);
    - [x] ✅ test_tcp_bind_ephemeral_port(&net, IpAddress::IPV6_UNSPECIFIED);
    - [x] ✅ test_tcp_bind_specific_port(&net, IpAddress::IPV4_LOOPBACK);
    - [x] ✅ test_tcp_bind_specific_port(&net, IpAddress::IPV6_LOOPBACK);
    - [x] ✅ test_tcp_bind_specific_port(&net, IpAddress::IPV4_UNSPECIFIED);
    - [x] ✅ test_tcp_bind_specific_port(&net, IpAddress::IPV6_UNSPECIFIED);
    - [x] ✅ test_tcp_bind_addrinuse(&net, IpAddress::IPV4_LOOPBACK);
    - [x] ✅ test_tcp_bind_addrinuse(&net, IpAddress::IPV6_LOOPBACK);
    - [x] ✅ test_tcp_bind_addrinuse(&net, IpAddress::IPV4_UNSPECIFIED);
    - [x] ✅ test_tcp_bind_addrinuse(&net, IpAddress::IPV6_UNSPECIFIED);
    - [x] ✅ test_tcp_bind_addrnotavail(&net, RESERVED_IPV4_ADDRESS);
    - [x] ✅ test_tcp_bind_addrnotavail(&net, RESERVED_IPV6_ADDRESS);
    - [x] ✅ test_tcp_bind_wrong_family(&net, IpAddressFamily::Ipv4);
    - [x] ✅ test_tcp_bind_wrong_family(&net, IpAddressFamily::Ipv6);
    - [x] ✅ test_tcp_bind_non_unicast(&net);
    - [x] ✅ test_tcp_bind_dual_stack(&net);
- [x] ✅ `preview2_tcp_connect`
    - [x] ✅ test_tcp_connect_unspec(&net, IpAddressFamily::Ipv4);
    - [x] ✅ test_tcp_connect_unspec(&net, IpAddressFamily::Ipv6);
    - [x] ✅ test_tcp_connect_port_0(&net, IpAddressFamily::Ipv4);
    - [x] ✅ test_tcp_connect_port_0(&net, IpAddressFamily::Ipv6);
    - [x] ✅ test_tcp_connect_wrong_family(&net, IpAddressFamily::Ipv4);
    - [x] ✅ test_tcp_connect_wrong_family(&net, IpAddressFamily::Ipv6);
    - [x] ✅ test_tcp_connect_non_unicast(&net);
    - [x] ⚠️ test_tcp_connect_dual_stack(&net); _(test passing but an error -49 is triggered - investigate))_
- [x] ❌ `preview2_tcp_sample_application`
   - [x] test_tcp_sample_application(ipv4...)
   - [x] test_tcp_sample_application(ipv6...)
- [x] ✅ `preview2_tcp_sockopts`
    - [x] ✅ test_tcp_sockopt_defaults(IpAddressFamily::Ipv4);
    - [x] ✅ test_tcp_sockopt_defaults(IpAddressFamily::Ipv6);
    - [x] ✅ test_tcp_sockopt_input_ranges(IpAddressFamily::Ipv4);
    - [x] ✅ test_tcp_sockopt_input_ranges(IpAddressFamily::Ipv6);
    - [x] ✅ test_tcp_sockopt_readback(IpAddressFamily::Ipv4);
    - [x] ✅ test_tcp_sockopt_readback(IpAddressFamily::Ipv6);
    - [x] ✅ test_tcp_sockopt_inheritance(&net, IpAddressFamily::Ipv4);
    - [x] ✅ test_tcp_sockopt_inheritance(&net, IpAddressFamily::Ipv6);
    - [x] ✅ test_tcp_sockopt_after_listen(&net, IpAddressFamily::Ipv4);
    - [x] ⚠️ test_tcp_sockopt_after_listen(&net, IpAddressFamily::Ipv6); _(test passing but an error -89 is triggered - investigate)_
- [x] ✅ `preview2_tcp_states`
    - [x] ✅ test_tcp_unbound_state_invariants(IpAddressFamily::Ipv4);
    - [x] ✅ test_tcp_unbound_state_invariants(IpAddressFamily::Ipv6);
    - [x] ✅ test_tcp_bound_state_invariants(&net, IpAddressFamily::Ipv4);
    - [x] ✅ test_tcp_bound_state_invariants(&net, IpAddressFamily::Ipv6);
    - [x] ✅ test_tcp_listening_state_invariants(&net, IpAddressFamily::Ipv4);
    - [x] ✅ test_tcp_listening_state_invariants(&net, IpAddressFamily::Ipv6);
    - [x] ⚠️ test_tcp_connected_state_invariants(&net, IpAddressFamily::Ipv4); _(test passing but an error -89 is triggered - investigate)_
    - [x] ⚠️ test_tcp_connected_state_invariants(&net, IpAddressFamily::Ipv6);  _(test passing but an error -89 is triggered - investigate)_

### UDP (??/33 tests)
- [x] `preview2_udp_bind` 
   - [x] ✅ test_udp_bind_ephemeral_port(&net, IpAddress::IPV4_LOOPBACK);
   - [x] ✅ test_udp_bind_ephemeral_port(&net, IpAddress::IPV6_LOOPBACK);
   - [x] ✅ test_udp_bind_ephemeral_port(&net, IpAddress::IPV4_UNSPECIFIED);
   - [x] ✅ test_udp_bind_ephemeral_port(&net, IpAddress::IPV6_UNSPECIFIED);
   - [x] ⚠️ test_udp_bind_specific_port(&net, IpAddress::IPV4_LOOPBACK); _(may fail on WSL when concurrent invocations to sock.blocking_bind())_
   - [x] ✅ test_udp_bind_specific_port(&net, IpAddress::IPV6_LOOPBACK);
   - [x] ✅ test_udp_bind_specific_port(&net, IpAddress::IPV4_UNSPECIFIED);
   - [x] ✅ test_udp_bind_specific_port(&net, IpAddress::IPV6_UNSPECIFIED);
   - [x] ✅ test_udp_bind_addrinuse(&net, IpAddress::IPV4_LOOPBACK);
   - [x] ✅ test_udp_bind_addrinuse(&net, IpAddress::IPV6_LOOPBACK);
   - [x] ✅ test_udp_bind_addrinuse(&net, IpAddress::IPV4_UNSPECIFIED);
   - [x] ✅ test_udp_bind_addrinuse(&net, IpAddress::IPV6_UNSPECIFIED);
   - [x] ✅ test_udp_bind_addrnotavail(&net, RESERVED_IPV4_ADDRESS);
   - [x] ✅ test_udp_bind_addrnotavail(&net, RESERVED_IPV6_ADDRESS);
   - [x] ✅ test_udp_bind_wrong_family(&net, IpAddressFamily::Ipv4);
   - [x] ✅ test_udp_bind_wrong_family(&net, IpAddressFamily::Ipv6);
   - [x] ✅ test_udp_bind_dual_stack(&net);
- [x] ❌ `preview2_udp_connect`
   - [ ] test_udp_connect_disconnect_reconnect(&net, IpAddressFamily::Ipv4);
   - [ ] test_udp_connect_disconnect_reconnect(&net, IpAddressFamily::Ipv6);
   - [ ] test_udp_connect_unspec(&net, IpAddressFamily::Ipv4);
   - [ ] test_udp_connect_unspec(&net, IpAddressFamily::Ipv6);
   - [ ] test_udp_connect_port_0(&net, IpAddressFamily::Ipv4);
   - [ ] test_udp_connect_port_0(&net, IpAddressFamily::Ipv6);
   - [ ] test_udp_connect_wrong_family(&net, IpAddressFamily::Ipv4);
   - [ ] test_udp_connect_wrong_family(&net, IpAddressFamily::Ipv6);
   - [ ] test_udp_connect_dual_stack(&net); 
- [x] ❌ `preview2_udp_sample_application`
   - [ ] test_udp_sample_application(ipv4...)
   - [ ] test_udp_sample_application(ipv6...)
   - [ ] test_udp_dual_stack_conversation()
- [x] ✅ `preview2_udp_sockopts`
    - [x] ✅ test_udp_sockopt_defaults(IpAddressFamily::Ipv4);
    - [x] ✅ test_udp_sockopt_defaults(IpAddressFamily::Ipv6);
    - [x] ✅ test_udp_sockopt_input_ranges(IpAddressFamily::Ipv4);
    - [x] ✅ test_udp_sockopt_input_ranges(IpAddressFamily::Ipv6);
    - [x] ✅ test_udp_sockopt_readback(IpAddressFamily::Ipv4);
    - [x] ✅ test_udp_sockopt_readback(IpAddressFamily::Ipv6);
- [x] ✅ `preview2_udp_states`
    - [x] ✅ test_udp_unbound_state_invariants(IpAddressFamily::Ipv4);
    - [x] ✅ test_udp_unbound_state_invariants(IpAddressFamily::Ipv6);
    - [x] ✅ test_udp_bound_state_invariants(&net, IpAddressFamily::Ipv4);
    - [x] ✅ test_udp_bound_state_invariants(&net, IpAddressFamily::Ipv6);
    - [x] ✅ test_udp_connected_state_invariants(&net, IpAddressFamily::Ipv4);
    - [x] ✅ test_udp_connected_state_invariants(&net, IpAddressFamily::Ipv6);

**Comment by manekinekko** [comment]
**Note 1:** Node.js does not expose libuv's setsocketopt() and getsocketopt(). We either submit a PR to Node.js or use 3rd party packages (ffi-napi and ref-napi), to expose socket libuv's bindings.

**Note 2:** what should be the exact behavior of client.stream(None)?

**Comment by manekinekko** [comment]
Notes from our last call on 27 Nov:
- Merge PR #214 as is to keep track of current progress on the confromance tests.
- Investigate weither we could use node:net and node:dgram for the TCP and UDP impl.
- Ask more clarity about client.stream(None) (on the wasi-sockets repo).
- We need to be able to support other JS runtimes, so avoid as much as we can depending on Node.js's libuv bindings.

@pchickey @guybedford @yoshuawuyts let's keep this issue open to track futures PRs.

**Comment by manekinekko** [comment]
Following our call from last week, here is a comparison of the Node.js socket APIs from `node:net`/`node:dgram` and the Node.js libuv's binding `tcp_wrap`/`udp_wrap`. I did my best to match the Node.js APIs to the libuv APIs, but I may have missed some. Please let me know if you think so.

As you can see from the table below, there are some APIs that are not exposed in `node:net`, for TCP: bind() and accept(). For UDP, both `node:dgram` and `udp_wrap` expose the same APIs.

After giving this some thought, and in order to meet our deadline, I think we should keep the current wasi-sockets implementation, based on `tcp_wrap` as is for now. We can still add support for other runtimes in the future, once we have a stable implementation for Node.js.


## TCP

| API                          | Node.js `node:net` (TCP)   | Node.js binding `tcp_wrap` | Notes                                                                                                                                        |
| ---------------------------- | -------------------------- | -------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------- |
| `*-bind`                     | N/A                        | `TCP.bind()`               |                                                                                                                                              |
| `*-connect`                  | `Socket.connect()`         | `TCP.connect()`            |                                                                                                                                              |
| `*-listen`                   | `Server.listen()`          | `TCP.listen()`             |                                                                                                                                              |
| `accept`                     | N/A                        | `TCP.accept()`             | Implicit accept() is called on `Server.on('connection')`                                                                                     |
| `local-address`              | `Socket.localAddress()`    | `TCP.getsockname()`        |                                                                                                                                              |
| `remote-address`             | `Socket.remoteAddress()`   | `TCP.getpeername()`        |                                                                                                                                              |
| `is-listening`               | `Server.listening`         | N/A                        |                                                                                                                                              |
| `address-family`             | `Socket.localFamily`       | `TCP.getsockname()`        |                                                                                                                                              |
| `[set-]ipv6-only`            | N/A                        | N/A                        | set via Server.listen() and uv__tcp_bind()                                                                                                   |
| `[set-]listen-backlog-size`  | N/A                        | N/A                        | set via Server.listen()                                                                                                                      |
| `[set-]keep-alive-enabled`   | `Socket.setKeepAlive()`    | `TCP.setKeepAlive()`       | Calling TCP.setKeepAlive() will set the following socket options: SO_KEEPALIVE=1, TCP_KEEPIDLE=initialDelay, TCP_KEEPCNT=10, TCP_KEEPINTVL=1 |
| `[set-]keep-alive-idle-time` | N/A                        | N/A                        |                                                                                                                                              |
| `[set-]keep-alive-interval`  | N/A                        | N/A                        |                                                                                                                                              |
| `[set-]keep-alive-count`     | N/A                        | N/A                        |                                                                                                                                              |
| `[set-]hop-limit`            | N/A                        | N/A                        |                                                                                                                                              |
| `[set-]receive-buffer-size`  | N/A                        | `TCP.bufferSize()`         |                                                                                                                                              |
| `[set-]send-buffer-size`     | N/A                        | `TCP.bufferSize()`         |                                                                                                                                              |
| `shutdown`                   | `Socket.destroySoon()` (?) | `TCP.shutdown()`           |                                                                                                                                              |


## UDP

| API                         | Node.js `node:dgram` (UDP)     | Node.js binding `udp_wrap`  | Notes |
| --------------------------- | ------------------------------ | --------------------------- | ----- |
| `*-bind`                    | `Socket.bind()`                | `UDP.bind()`                |       |
| `stream`                    | `Socket.connect()`             | `UDP.connect()`             |       |
| `local-address`             | `Socket.address()`             | `UDP.getsockname()`         |       |
| `remote-address`            | `Socket.remoteAddress()`       | `UDP.getpeername()`         |       |
| `address-family`            | `Socket.address().family`      | `UDP.getsockname().family`  |       |
| `[set-]unicast-hop-limit`   | `Socket.setTTL()`              | `UDP.setTTL()`              |       |
| `[set-]receive-buffer-size` | `Socket.[set]RecvBufferSize()` | `UDP.bufferSize(SO_RCVBUF)` |       |
| `[set-]send-buffer-size`    | `Socket.[set]SendBufferSize()` | `UDP.bufferSize(SO_SNDBUF)` |       |

**Comment by guybedford** [comment]
I think `accept` is just a synchronous version of the listen callback, which we can do with the IO thread. And similarly, `bind` is the listen call itself, without the callback being called.

As such I see no reason not to use the `net` implementation here, and would recommend we pair on this next week if you have some time then.

**Comment by guybedford** [comment]
Just to update the report here, on my latest test run, I'm still getting the following test cases failing:

* cli_no_ip_name_lookup
* cli_no_tcp
* cli_no_udp
* preview2_ip_name_lookup
* preview2_tcp_sample_application
* preview2_tcp_sockopts
* preview2_tcp_states
* preview2_udp_bind
* preview2_udp_connect
* preview2_udp_sample_application
* preview2_udp_sockopts
* preview2_udp_states

Any updates very much welcome if I'm missing something.

**Comment by guybedford** [comment]
I've resolved the three deny tests in https://github.com/bytecodealliance/jco/pull/310 - `cli_no_ip_name_lookup`, `cli_no_tcp` and `cli_no_udp` are now passing there
