### ISSUE TITLE
Jco transpile: implementation of wasi-http for Web

### ISSUE THREAD

**Issue by pchickey** [bytecodealliance/jco#155]
Targets ServiceWorker, Fetch.

## Tasks

- [ ] `incoming-handler.handle`
- [ ] `outgoing-handler.handle`
- [ ] `types.drop-fields`
- [ ] `types.new-fields`
- [ ] `types.fields-get`
- [ ] `types.fields-set`
- [ ] `types.fields-delete`
- [ ] `types.fields-append`
- [ ] `types.fields-entries`
- [ ] `types.fields-clone`
- [ ] `types.finish-incoming-stream`
- [ ] `types.finish-outgoing-stream`
- [ ] `types.drop-incoming-request`
- [ ] `types.drop-outgoing-request`
- [ ] `types.incoming-request-method`
- [ ] `types.incoming-request-path-with-query`
- [ ] `types.incoming-request-scheme`
- [ ] `types.incoming-request-authority`
- [ ] `types.incoming-request-headers`
- [ ] `types.incoming-request-consume`
- [ ] `types.new-outgoing-request`
- [ ] `types.outgoing-request-write`
- [ ] `types.drop-response-outparam`
- [ ] `types.set-response-outparam`
- [ ] `types.drop-incoming-response`
- [ ] `types.incoming-response-status`
- [ ] `types.incoming-response-headers`
- [ ] `types.incoming-response-consume`
- [ ] `types.drop-outgoing-response`
- [ ] `types.new-outgoing-response`
- [ ] `types.outgoing-response-write`
- [ ] `types.future-incoming-response-get`
- [ ] `types.drop-future-incoming-response`
- [ ] `types.listen-to-future-incoming-response`

**Comment by vados-cosmonic** [comment]
This was addressed by https://github.com/bytecodealliance/jco/pull/1907
