### ISSUE TITLE
Jco transpile: implementation of wasi-cli for Node.js

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/jco#200]
## Tasks
- [x] `environment.get-environment`
- [x] `environment.get-arguments`
- [x] `environment.initial-cwd`
- [x] `exit.exit`
- [x] `run.run`
- [x] `stdin.get-stdin`
- [x] `stdout.get-stdout`
- [x] `stderr.get-stderr`
- [x] `terminal-stdin.get-terminal-stdin`
- [x] `terminal-stdout.get-terminal-stdout`
- [x] `terminal-stderr.get-terminal-stderr`

## Conformance Tests
- [x] `cli_args`
- [x] `cli_env`
- [x] `cli_exit_default`
- [x] `cli_exit_failure`
- [x] `cli_exit_panic`
- [x] `cli_exit_success`
- [x] `cli_hello_stdout`
- [x] `cli_splice_stdin`
- [x] `cli_stdin`
- [x] `preview1_poll_oneoff_stdio`
- [x] `preview1_stdio`
- [x] `preview1_stdio_isatty`
- [x] `preview1_stdio_not_isatty`
- [x] `preview1_unicode_output`
- [x] `preview2_stream_pollable_correct`
- [x] `preview2_stream_pollable_traps`

**Comment by guybedford** [comment]
I've updated the status on these. We should figure out what the requirements are for `drop-terminal-input` to finalize this item.

**Comment by guybedford** [comment]
Completed in https://github.com/bytecodealliance/jco/pull/290.
