### ISSUE TITLE
Jco transpile: implementation of wasi-clocks for Node.js

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/jco#201]
## Tasks

- [x] `monotonic-clock.now`
- [x] `monotonic-clock.resolution`
- [x] `monotonic-clock.subscribeInstant`
- [x] `monotonic-clock.subscribeDuration`
- [x] `wallclock.now`
- [x] `wallclock.resolution`

## Conformance Tests
- [x] `api_time`
- [x] `cli_default_clocks`
- [x] `preview1_clock_time_get`
- [x] `preview2_sleep`

**Comment by yoshuawuyts** [comment]
I'm currently working on this one.
