### ISSUE TITLE
Jco transpile: implementation of wasi-clocks for Web

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/jco#202]
## Tasks

- [x] `monotonic-clock.now`
- [ ] `monotonic-clock.resolution`
- [ ] `monotonic-clock.subscribe`
- [ ] `timezone.display`
- [ ] `timezone.utc-offset`
- [ ] `timezone.drop-timezone`
- [x] `wallclock.now`
- [ ] `wallclock.resolution`
