### ISSUE TITLE
Jco transpile: implementation of wasi-filesystem for Node.js

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/jco#203]
## Tasks

- [x] `preopens.get-directories`
- [x] `types.descriptor.read-via-stream`
- [x] `types.descriptor.write-via-stream`
- [x] `types.descriptor.append-via-stream`
- [x] `types.descriptor.advise`
- [x] `types.descriptor.sync-data`
- [x] `types.descriptor.get-flags`
- [x] `types.descriptor.get-type`
- [x] `types.descriptor.set-size`
- [x] `types.descriptor.set-times`
- [x] `types.descriptor.read`
- [x] `types.descriptor.write`
- [x] `types.descriptor.read-directory`
- [x] `types.descriptor.sync`
- [x] `types.descriptor.create-directory-at`
- [x] `types.descriptor.stat`
- [x] `types.descriptor.stat-at`
- [x] `types.descriptor.set-times-at`
- [x] `types.descriptor.link-at`
- [x] `types.descriptor.open-at`
- [x] `types.descriptor.readlink-at`
- [x] `types.descriptor.remove-directory-at`
- [x] `types.descriptor.rename-at`
- [x] `types.descriptor.symlink-at`
- [x] `types.descriptor.access-at`
- [x] `types.descriptor.unlink-file-at`
- [x] `types.descriptor.is-same-object`
- [x] `types.descriptor.metadata-hash`
- [x] `types.descriptor.metadata-hash-at`
- [x] `types.directory-entry-stream.read-directory-entry`
- [x] `types.filesystem-error-code`

## Conformance Tests
- [x] `api_read_only`
- [x] `cli_directory_list`
- [x] `cli_file_append`
- [x] `cli_file_dir_sync`
- [x] `cli_file_read`
- [x] `preview1_close_preopen`
- [x] `preview1_dangling_fd`
- [x] `preview1_dangling_symlink`
- [x] `preview1_dir_fd_op_failures`
- [x] `preview1_directory_seek`
- [x] `preview1_fd_advise`
- [x] `preview1_fd_filestat_get`
- [x] `preview1_fd_filestat_set`
- [x] `preview1_fd_flags_set`
- [x] `preview1_fd_readdir`
- [x] `preview1_file_allocate`
- [x] `preview1_file_pread_pwrite`
- [x] `preview1_file_seek_tell`
- [x] `preview1_file_truncation`
- [x] `preview1_file_unbuffered_write`
- [x] `preview1_interesting_paths`
- [x] `preview1_nofollow_errors`
- [x] `preview1_overwrite_preopen`
- [x] `preview1_path_exists`
- [x] `preview1_path_filestat`
- [x] `preview1_path_link`
- [x] `preview1_path_open_create_existing`
- [x] `preview1_path_open_dirfd_not_dir`
- [x] `preview1_path_open_missing`
- [x] `preview1_path_open_nonblock`
- [x] `preview1_path_open_preopen`
- [x] `preview1_path_open_read_write`
- [x] `preview1_path_rename`
- [x] `preview1_path_rename_dir_trailing_slashes`
- [x] `preview1_path_rename_file_trailing_slashes`
- [x] `preview1_path_symlink_trailing_slashes`
- [x] `preview1_poll_oneoff_files`
- [x] `preview1_readlink`
- [x] `preview1_regular_file_isatty`
- [x] `preview1_remove_directory_trailing_slashes`
- [x] `preview1_remove_nonempty_directory`
- [x] `preview1_renumber`
- [x] `preview1_symlink_create`
- [x] `preview1_symlink_filestat`
- [x] `preview1_symlink_loop`
- [x] `preview1_unlink_file_trailing_slashes`

**Comment by yoshuawuyts** [comment]
To implement the lock functions, we can probably (re)-use https://www.npmjs.com/package/fd-lock

**Comment by manekinekko** [comment]
Looks like lock methods [have been removed](https://github.com/WebAssembly/wasi-filesystem/pull/136) from Preview 2 for now.

**Comment by yoshuawuyts** [comment]
From today's sync meeting: once #244 this should mostly be an exercise in checkboxes. Implement a function, write a test, check in.
