### ISSUE TITLE
Jco transpile: implementation of wasi-http for Node.js

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/jco#204]
## Tasks

- [x] `incoming-handler.handle`
- [x] `outgoing-handler.handle`
- [x] `types.drop-fields`
- [x] `types.new-fields`
- [x] `types.fields-get`
- [x] `types.fields-set`
- [x] `types.fields-delete`
- [x] `types.fields-append`
- [x] `types.fields-entries`
- [x] `types.fields-clone`
- [x] `types.finish-incoming-stream`
- [x] `types.finish-outgoing-stream`
- [x] `types.drop-incoming-request`
- [x] `types.drop-outgoing-request`
- [x] `types.incoming-request-method`
- [x] `types.incoming-request-path-with-query`
- [x] `types.incoming-request-scheme`
- [x] `types.incoming-request-authority`
- [x] `types.incoming-request-headers`
- [x] `types.incoming-request-consume`
- [x] `types.new-outgoing-request`
- [x] `types.outgoing-request-write`
- [x] `types.drop-response-outparam`
- [x] `types.set-response-outparam`
- [x] `types.drop-incoming-response`
- [x] `types.incoming-response-status`
- [x] `types.incoming-response-headers`
- [x] `types.incoming-response-consume`
- [x] `types.drop-outgoing-response`
- [x] `types.new-outgoing-response`
- [x] `types.outgoing-response-write`
- [x] `types.future-incoming-response-get`
- [ ] `types.request-options`
- [ ] `types.future-trailers-subscribe`
- [x] `types.drop-future-incoming-response`
- [x] `types.listen-to-future-incoming-response`

## Conformance Tests

- [x] `api_proxy`
- [x] `api_proxy_streaming`
- [x] `http_outbound_request_content_length`
- [x] `http_outbound_request_get`
- [x] `http_outbound_request_invalid_dnsname`
- [x] `http_outbound_request_invalid_header`
- [x] `http_outbound_request_invalid_port`
- [x] `http_outbound_request_invalid_version`
- [x] `http_outbound_request_large_post`
- [x] `http_outbound_request_post`
- [x] `http_outbound_request_put`
- [x] `http_outbound_request_response_build`
- [x] `http_outbound_request_unknown_method`
- [x] `http_outbound_request_unsupported_scheme`

**Comment by guybedford** [comment]
Completed in https://github.com/bytecodealliance/jco/pull/317.
