### ISSUE TITLE
Jco transpile: implementation of wasi-io for Node.js

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/jco#206]
## Tasks

- [x] `streams.read`
- [x] `streams.blocking-read`
- [ ] `streams.skip`
- [ ] `streams.blocking-skip`
- [ ] `streams.subscribe-to-input-stream`
- [x] `streams.drop-input-stream`
- [x] `streams.check-write`
- [x] `streams.write`
- [x] `streams.blocking-write-and-flush`
- [x] `streams.flush`
- [x] `streams.blocking-flush`
- [ ] `streams.subscribe-to-output-stream`
- [ ] `streams.write-zeroes`
- [ ] `streams.splice`
- [ ] `streams.blocking-splice`
- [ ] `streams.forward`
- [x] `streams.drop-output-stream`
- [ ] `poll.drop-pollable`
- [ ] `poll.poll-oneoff`

**Comment by guybedford** [comment]
Full implementation in https://github.com/bytecodealliance/jco/pull/244.

**Comment by yoshuawuyts** [comment]
These should all be closed by #244, the only missing part is adding tests.
